module.exports = {
	bins: require("./bins"),
	cookies: require("./cookies"),
	delay: require("./delay"),
	echo: require("./echo"),
	gzip: require("./gzip"),
	har: require("./har"),
	headers: require("./headers"),
	hello: require("./hello"),
	ips: require("./ips"),
	redirect: require("./redirect"),
	request: require("./request"),
	status: require("./status"),
	stream: require("./stream"),
};
