name: Audit

on:
  # push:
  pull_request:
    # paths:
    #   - "**/package-lock.json"
    #   - "**/audit.yml"

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v2.4.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_pr_comments: true
          audit_level: high
