name: SAST

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    tags:
    - 'v*.*.*'  
  workflow_dispatch: {}

permissions: {} # Deny all GITHUB_TOKEN permissions by default.

jobs:
  semgrep:
    timeout-minutes: ${{ fromJSON(vars.GHA_DEFAULT_TIMEOUT) }}
    name: Semgrep SAST
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      contents: read

    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            metrics.semgrep.dev:443
            semgrep.dev:443
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: Kong/public-shared-actions/security-actions/semgrep@a18abf762d6e2444bcbfd20de70451ea1e3bc1b1 # v4.0.1
